name: Django CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change the directory to the level-9 directory
        run: cd level9
      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests with coverage
        run: |
          coverage run manage.py test
      - name: coverage report
        run: |
          coverage report
